sudo: required
services:
  - docker
before_install:
  - docker build -t sazz/sample .
deploy:
  access_key_id: $AWS_ACCESS_KEY
  app: "sample-dev"
  bucket_name: "elasticbeanstalk-us-east-2-278338191187"
  bucket_path: sample
  env: "SampleDev-env"
  provider: elasticbeanstalk
  region: "us-east-2"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  on:
    branch: master
