sudo: required

services:
  - docker

before_install:
  - docker build -t sazz/sample .

script:
  - docker run -t sazz/sample

deploy:
  provider; 'elasticbeanstalk'
  region: 'us-east-2'
  app: 'sample-dev'
  env: 'SampleDev-env'
  bucket_name: 'elasticbeanstalk-us-east-2-278338191187'
  bucket_path: 'sample'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"