sudo: required

services:
  - docker

before_install:
  - docker build -t sazz/sample .

deploy:
  provider; 'elasticbeanstalk'
  region: 'us-east-2'
  app: 'sample-dev'
  env: 'SampleDev-env'
  bucket_name: 'elasticbeanstalk-us-east-2-278338191187'
  bucket_path: 'sample'
  on:
    branch: 'master'
  